# Generated by Django 5.1.15 on 2026-04-16 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0005_oauthexchangecode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("embedding_vector", models.BinaryField(blank=True, null=True)),
                ("page_number", models.IntegerField(default=0)),
                ("section_title", models.CharField(blank=True, max_length=255)),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[
                            ("text", "Paragraph Text"),
                            ("table", "Table"),
                            ("math", "Mathematical Content"),
                            ("figure_caption", "Figure Caption"),
                            ("external", "External Source"),
                        ],
                        default="text",
                        max_length=50,
                    ),
                ),
                (
                    "citation_anchors",
                    models.JSONField(
                        default=list, help_text="Source citations within this chunk"
                    ),
                ),
                (
                    "source_chunk_id",
                    models.CharField(
                        db_index=True,
                        help_text="Format: doc_{doc_id}_chunk_{index}",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chunk Index",
                "verbose_name_plural": "Chunk Indexes",
            },
        ),
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authors",
                    models.JSONField(
                        default=list, help_text="[{'name': '', 'affiliation': ''}, ...]"
                    ),
                ),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("doi", models.CharField(blank=True, db_index=True, max_length=255)),
                ("abstract", models.TextField(blank=True)),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="['keyword1', 'keyword2', ...]"
                    ),
                ),
                ("total_sections", models.IntegerField(default=0)),
                ("total_tables", models.IntegerField(default=0)),
                ("total_figures", models.IntegerField(default=0)),
                ("has_math", models.BooleanField(default=False)),
                ("references_found", models.IntegerField(default=0)),
                (
                    "bibtex_entries",
                    models.JSONField(
                        default=dict, help_text="BibTeX entries indexed by citation key"
                    ),
                ),
                ("avg_chunk_quality_score", models.FloatField(default=0.0)),
                ("parsing_issues", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailLoginToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QueryEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField()),
                ("answer_text", models.TextField()),
                ("citations_count", models.IntegerField(default=0)),
                ("citations_valid_count", models.IntegerField(default=0)),
                ("citations_invalid_count", models.IntegerField(default=0)),
                ("faithfulness_score", models.FloatField(default=0.0)),
                ("relevancy_score", models.FloatField(default=0.0)),
                ("context_precision", models.FloatField(default=0.0)),
                (
                    "model_used",
                    models.CharField(default="azure_openai", max_length=100),
                ),
                ("chunks_used", models.IntegerField(default=0)),
                ("processing_time_ms", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=8),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="externalauthidentity",
            new_name="ai_engine_e_provide_b20595_idx",
            old_name="ai_engine_e_provider_6c98a3_idx",
        ),
        migrations.RenameIndex(
            model_name="externalauthidentity",
            new_name="ai_engine_e_user_id_b40905_idx",
            old_name="ai_engine_e_user_id_369b17_idx",
        ),
        migrations.RenameIndex(
            model_name="oauthexchangecode",
            new_name="ai_engine_o_expires_b31945_idx",
            old_name="ai_engine_o_expires_5edfe0_idx",
        ),
        migrations.RenameIndex(
            model_name="oauthexchangecode",
            new_name="ai_engine_o_user_id_697776_idx",
            old_name="ai_engine_o_user_id_6c1f52_idx",
        ),
        migrations.AddField(
            model_name="document",
            name="encrypted_content",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="encryption_version",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Encryption algorithm version"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="is_encrypted",
            field=models.BooleanField(
                default=False, help_text="Whether document content is encrypted at rest"
            ),
        ),
        migrations.AddField(
            model_name="chunkindex",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for external discovery results",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="ai_engine.document",
            ),
        ),
        migrations.AddField(
            model_name="documentmetadata",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="ai_engine.document",
            ),
        ),
        migrations.AddField(
            model_name="emaillogintoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_login_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="queryevaluation",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_engine.document",
            ),
        ),
        migrations.AddField(
            model_name="queryevaluation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_evaluations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chunkindex",
            index=models.Index(
                fields=["document", "page_number"],
                name="ai_engine_c_documen_902c4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chunkindex",
            index=models.Index(
                fields=["user_id", "chunk_type"], name="ai_engine_c_user_id_1df97f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chunkindex",
            index=models.Index(
                fields=["source_chunk_id"], name="ai_engine_c_source__c72f12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillogintoken",
            index=models.Index(
                fields=["expires_at"], name="ai_engine_e_expires_fab499_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillogintoken",
            index=models.Index(
                fields=["email", "expires_at"], name="ai_engine_e_email_064492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryevaluation",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_engine_q_user_id_fe3406_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queryevaluation",
            index=models.Index(
                fields=["document", "-created_at"],
                name="ai_engine_q_documen_2cd07d_idx",
            ),
        ),
    ]
