# Generated by Django 5.2.12 on 2026-04-18 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_chunkindex_documentmetadata_emaillogintoken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('semantic-scholar', 'Semantic Scholar'), ('arxiv', 'arXiv'), ('crossref', 'CrossRef'), ('google-scholar', 'Google Scholar'), ('manual', 'Manual Upload')], max_length=20)),
                ('authors', models.JSONField(default=list)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255)),
                ('citation_count', models.IntegerField(default=0)),
                ('h_index_contribution', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publication_year', '-citation_count'],
            },
        ),
        migrations.CreateModel(
            name='PaperLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_favorite', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sources_cited', models.JSONField(default=list)),
                ('faithfulness_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('method', models.CharField(choices=[('direct_retrieval', 'Direct Retrieval'), ('llm_synthesis', 'LLM Synthesis'), ('rejected', 'Rejected')], max_length=50)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('latency_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('potential_research_directions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('relevance_score', models.FloatField(default=0.0)),
                ('relevance_reason', models.TextField()),
                ('key_challenges', models.JSONField(default=list)),
                ('skills_needed', models.JSONField(default=list)),
                ('related_fields', models.JSONField(default=list)),
                ('papers_count', models.IntegerField(default=0)),
                ('growth_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chunkindex',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chunkindex',
            name='ai_engine_c_documen_902c4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='chunkindex',
            name='ai_engine_c_user_id_1df97f_idx',
        ),
        migrations.RemoveIndex(
            model_name='chunkindex',
            name='ai_engine_c_source__c72f12_idx',
        ),
        migrations.RemoveField(
            model_name='chunkindex',
            name='chunk_type',
        ),
        migrations.RemoveField(
            model_name='chunkindex',
            name='citation_anchors',
        ),
        migrations.RemoveField(
            model_name='chunkindex',
            name='embedding_vector',
        ),
        migrations.RemoveField(
            model_name='chunkindex',
            name='section_title',
        ),
        migrations.RemoveField(
            model_name='chunkindex',
            name='source_chunk_id',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='avg_chunk_quality_score',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='doi',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='has_math',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='parsing_issues',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='references_found',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='total_figures',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='total_sections',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='total_tables',
        ),
        migrations.RemoveField(
            model_name='documentmetadata',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='chunkindex',
            name='citation_keys',
            field=models.JSONField(default=list, help_text='List of BibTeX keys cited in this chunk'),
        ),
        migrations.AddField(
            model_name='chunkindex',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chunkindex',
            name='is_qa',
            field=models.BooleanField(default=False, help_text='True if this chunk looks like Q&A pair - can return directly'),
        ),
        migrations.AlterField(
            model_name='chunkindex',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_engine.document'),
        ),
        migrations.AddIndex(
            model_name='chunkindex',
            index=models.Index(fields=['user_id', 'document'], name='ai_engine_c_user_id_73f7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkindex',
            index=models.Index(fields=['user_id', 'is_qa'], name='ai_engine_c_user_id_d19a93_idx'),
        ),
        migrations.AddField(
            model_name='academicpaper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paperlibrary',
            name='papers',
            field=models.ManyToManyField(blank=True, related_name='libraries', to='ai_engine.academicpaper'),
        ),
        migrations.AddField(
            model_name='paperlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_libraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paperqna',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna', to='ai_engine.academicpaper'),
        ),
        migrations.AddField(
            model_name='paperqna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_qna', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchgap',
            name='supporting_papers',
            field=models.ManyToManyField(blank=True, to='ai_engine.academicpaper'),
        ),
        migrations.AddField(
            model_name='researchgap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_gaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchgap',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='ai_engine.researchtopic'),
        ),
        migrations.DeleteModel(
            name='QueryEvaluation',
        ),
        migrations.AddIndex(
            model_name='academicpaper',
            index=models.Index(fields=['user', '-created_at'], name='ai_engine_a_user_id_a7db9e_idx'),
        ),
        migrations.AddIndex(
            model_name='academicpaper',
            index=models.Index(fields=['user', 'source'], name='ai_engine_a_user_id_8bf8b3_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['user', '-created_at'], name='ai_engine_q_user_id_05e0cc_idx'),
        ),
    ]
