# Generated by Django 5.2.13 on 2026-04-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0007_academicpaper_paperlibrary_paperqna_querylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Text content for external papers (abstract, summary, etc.)'),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('upload', 'User Upload'), ('semantic_scholar', 'Semantic Scholar'), ('arxiv', 'arXiv'), ('crossref', 'CrossRef')], default='upload', help_text='Where this document came from', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='External metadata: {paper_id, external_url, original_url, authors, year, venue, doi}'),
        ),
    ]
